package com.aidriven.spi.provider;

import com.aidriven.spi.model.OperationContext;
import java.util.List;
import java.util.Map;

/**
 * Service Provider Interface (SPI) for AI chat model backends.
 *
 * <p>This is the low-level provider contract that decouples the core agent
 * framework from specific AI model SDKs. Each implementation wraps a specific
 * AI service SDK and translates between the provider-neutral message format
 * and the SDK's native API.</p>
 *
 * <h3>Known Implementations</h3>
 * <ul>
 *   <li>{@code SpringAiClientAdapter} -- Anthropic via Spring AI
 *       ({@code AnthropicChatModel} and {@code AnthropicApi})</li>
 *   <li>{@code BedrockClient} -- Anthropic Claude via AWS Bedrock runtime</li>
 * </ul>
 *
 * <h3>Message Format</h3>
 * <p>Messages follow the Claude Messages API structure: each message is a
 * {@code Map} with {@code "role"} and {@code "content"} keys. Content can be
 * a simple string or a list of content blocks ({@code text}, {@code tool_use},
 * {@code tool_result}).</p>
 *
 * <h3>Tool Definition Format</h3>
 * <p>Tools are defined as maps with {@code "name"}, {@code "description"},
 * and {@code "input_schema"} (JSON Schema). This format is intentionally
 * SDK-neutral to allow the SPI module to remain free of SDK dependencies.</p>
 *
 * @see com.aidriven.spi.model.OperationContext
 * @since 1.0
 */
public interface AiProvider {

    /**
     * Returns the unique identifier for this provider.
     *
     * <p>Used by the factory to select the appropriate provider based on
     * configuration (e.g., the {@code CLAUDE_PROVIDER} environment variable).</p>
     *
     * @return the provider identifier (e.g., {@code "claude"}, {@code "bedrock"},
     *         {@code "spring_ai"}); never {@code null}
     */
    String getName();

    /**
     * Sends a chat request to the AI model with optional tool definitions and
     * returns the model's response.
     *
     * <p>Implementations must handle:
     * <ul>
     *   <li>Constructing the native API request from the provider-neutral format</li>
     *   <li>Retry logic for transient failures (rate limits, timeouts)</li>
     *   <li>Mapping the native response back to {@link ChatResponse}</li>
     * </ul>
     *
     * @param context      the operation context carrying tenant and tracing
     *                     information; never {@code null}
     * @param systemPrompt the system-level instruction for the model;
     *                     never {@code null}
     * @param messages     the conversation history in Claude Messages API format
     * @param tools        tool definitions in Claude API format; may be empty if
     *                     no tools are available for this request
     * @return the model's response wrapped in a {@link ChatResponse};
     *         never {@code null}
     */
    ChatResponse chat(OperationContext context, String systemPrompt, List<Map<String, Object>> messages,
            List<Map<String, Object>> tools);

    /**
     * SDK-neutral container for an AI model chat response.
     *
     * <p>This interface abstracts away SDK-specific response classes (e.g.,
     * Spring AI's {@code ChatResponse}, Bedrock's {@code InvokeModelResponse})
     * to keep the SPI module free of third-party dependencies. Implementations
     * map their SDK's native response to this interface.</p>
     *
     * @since 1.0
     */
    interface ChatResponse {

        /**
         * Returns the text content from the model's response.
         *
         * <p>If the response contains multiple text blocks, they are
         * concatenated. If the response contains only tool calls with no text,
         * this may return an empty string.</p>
         *
         * @return the text content; never {@code null}
         */
        String getText();

        /**
         * Returns the tool calls requested by the model, if any.
         *
         * <p>Each tool call is a map with {@code "id"} (correlation ID),
         * {@code "name"} (tool name), and {@code "input"} (arguments object).
         * Returns an empty list if the model did not request any tool calls.</p>
         *
         * @return the list of tool call maps; never {@code null}
         */
        List<Map<String, Object>> getToolCalls();

        /**
         * Returns the number of input tokens consumed by the request
         * (prompt, conversation history, and tool definitions).
         *
         * @return the input token count
         */
        int getInputTokens();

        /**
         * Returns the number of output tokens generated by the model.
         *
         * @return the output token count
         */
        int getOutputTokens();
    }
}
