package com.aidriven.core.notification;

import com.aidriven.spi.notification.ApprovalNotifier;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@Slf4j
public class SlackNotifier implements ApprovalNotifier {

    private final HttpClient httpClient;
    private final String webhookUrl;
    private final Optional<String> targetChannel;
    private final ObjectMapper objectMapper;

    public SlackNotifier(HttpClient httpClient, String webhookUrl, Optional<String> targetChannel) {
        this.httpClient = httpClient;
        this.webhookUrl = webhookUrl;
        this.targetChannel = targetChannel;
        this.objectMapper = new ObjectMapper();
    }

    @Override
    public void notifyPending(PendingApprovalContext context) {
        if (webhookUrl == null || webhookUrl.isBlank()) {
            log.warn("Slack webhook URL is empty, skipping notification for ticket={}", context.ticketKey());
            return;
        }

        try {
            String jsonPayload = buildPayload(context);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(webhookUrl))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                    .build();

            log.info("Sending Slack approval notification for ticket={}", context.ticketKey());

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() >= 400) {
                log.error("Failed to send Slack notification. Status: {}, Body: {}",
                        response.statusCode(), response.body());
                throw new RuntimeException("Slack API error: " + response.statusCode());
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            log.error("Slack notification interrupted for ticket={}", context.ticketKey(), e);
            throw new RuntimeException("Slack notification interrupted", e);
        } catch (Exception e) {
            log.error("Failed to send Slack notification for ticket={}", context.ticketKey(), e);
            if (e instanceof RuntimeException re) {
                throw re;
            }
            throw new RuntimeException("Failed to send Slack notification", e);
        }
    }

    // Visible for testing
    String buildPayload(PendingApprovalContext context) throws JsonProcessingException {
        long timeoutHours = context.timeoutSeconds() / 3600;

        String markdownText = String.format(
                "🚨 *[AI Agent] HIGH RISK ACTION pending for ticket %s*\n" +
                        "• *Action*: %s\n" +
                        "• *Reason*: %s\n" +
                        "• *Context*: Generated by %s on ticket %s\n" +
                        "• *Approve*: Reply `@ai approve` in Jira comment\n" +
                        "• *Reject*: Reply `@ai reject` with reason\n" +
                        "• *Timeout*: %dh",
                context.ticketKey(),
                context.actionDescription(),
                context.triggerReason(),
                context.generatedByModel(),
                context.ticketKey(),
                timeoutHours);

        Map<String, Object> payload = new HashMap<>();
        payload.put("text", markdownText);

        targetChannel.ifPresent(ch -> payload.put("channel", ch));

        return objectMapper.writeValueAsString(payload);
    }
}
