package com.aidriven.core.config;

import java.util.Optional;
import lombok.Builder;
import lombok.Getter;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Getter
@Builder(toBuilder = true)
@AllArgsConstructor
@Slf4j
public class AppConfig {

    private static final AppConfig INSTANCE = ConfigLoader.loadFromEnv();

    public static AppConfig getInstance() {
        return INSTANCE;
    }

    private final String dynamoDbTableName;
    private final String claudeSecretArn;
    private final String bitbucketSecretArn;
    private final String jiraSecretArn;
    private final String codeContextBucket;
    @lombok.Getter(lombok.AccessLevel.NONE)
    private final String stateMachineArn;
    private final int maxContextForClaude;
    private final String claudeModel;
    /**
     * Fallback Claude model for complex/precision tasks (e.g. claude-opus-4-6).
     * Per ADR-012: Sonnet is the default; Opus is the precision escalation.
     * Populated from CLAUDE_MODEL_FALLBACK env var.
     */
    private final String claudeModelFallback;
    private final String claudeResearcherModel;
    private final int claudeResearcherMaxTokens;
    private final int claudeMaxTokens;
    private final double claudeTemperature;
    private final String promptVersion;
    /**
     * Claude provider: ANTHROPIC_API or BEDROCK.
     * Populated from CLAUDE_PROVIDER env var (default: ANTHROPIC_API).
     */
    private final String claudeProvider;
    /**
     * AWS region for BedRock (when CLAUDE_PROVIDER=BEDROCK).
     * Populated from BEDROCK_REGION env var (default: us-east-1).
     */
    private final String bedrockRegion;
    private final String branchPrefix;
    private final String gitHubSecretArn;
    private final String jiraWebhookSecret;
    /**
     * ARN of the Secrets Manager secret holding the Jira webhook pre-shared token.
     */
    private final String jiraWebhookSecretArn;
    /**
     * ARN of the Secrets Manager secret holding the GitHub agent webhook HMAC
     * secret.
     */
    private final String gitHubAgentWebhookSecretArn;
    private final String defaultPlatform;
    private final String defaultWorkspace;
    private final String defaultRepo;
    /**
     * Maximum characters per individual source file (immutable at construction
     * time).
     */
    private final int maxFileSizeChars;
    /**
     * Maximum total characters of all source files combined (immutable at
     * construction time).
     */
    private final int maxTotalContextChars;
    /**
     * Maximum file size in bytes for context file filtering (immutable at
     * construction time).
     * Populated from MAX_FILE_SIZE_BYTES env var (default 500_000).
     */
    private final long maxFileSizeBytes;
    /**
     * Context strategy mode — populated once at construction time from CONTEXT_MODE
     * env var.
     * Defaults to INCREMENTAL per ADR-013. Use getContextMode() to access.
     */
    private final ContextMode contextMode;

    private final String slackWebhookUrl;
    private final String slackChannel;
    private final boolean slackFallbackToJira;

    /**
     * Whether cost-aware mode is enabled (impl-12).
     * When true, the handler estimates tokens before invoking the model and may
     * downgrade context or reject tasks that would exceed budget.
     */
    private final boolean costAwareMode;
    /**
     * Monthly budget ceiling in USD (impl-12).
     * The handler aborts if accumulated spend >= this value.
     */
    private final double monthlyBudgetUsd;
    /**
     * Per-ticket maximum token cap (impl-12).
     * If total tokens for a ticket would exceed this, the handler downgrades
     * context or rejects the task.
     */
    private final int maxTokensPerTicket;

    private final int maxRequestsPerUserPerHour;
    private final int maxRequestsPerTicketPerHour;

    /**
     * Maximum file size in characters before summarization is applied (impl-22).
     * Files larger than this threshold will be structurally summarized before
     * being sent to the model. Set to Integer.MAX_VALUE to disable summarization.
     * Populated from SUMMARIZATION_THRESHOLD env var (default: 50 000).
     */
    private final int summarizationThreshold;

    /**
     * Loads configuration from environment variables.
     * 
     * @deprecated Use {@link ConfigLoader#loadFromEnv()} instead
     */
    @Deprecated
    private static AppConfig loadFromEnv() {
        return ConfigLoader.loadFromEnv();
    }

    // Configurable Limits with Defaults
    // NOTE: getters for maxFileSizeChars and maxTotalContextChars are generated by
    // @Getter
    // (fields are now final and set at construction time by ConfigLoader).

    public SlackConfig getSlackConfig() {
        return new SlackConfig(
                Optional.ofNullable(slackWebhookUrl).filter(s -> !s.isBlank()),
                Optional.ofNullable(slackChannel).filter(s -> !s.isBlank()),
                slackFallbackToJira);
    }

    public ClaudeConfig getClaudeConfig() {
        return new ClaudeConfig(
                maxContextForClaude,
                claudeModel,
                claudeMaxTokens,
                claudeTemperature,
                promptVersion,
                claudeSecretArn,
                claudeModelFallback,
                claudeResearcherModel,
                claudeResearcherMaxTokens,
                claudeProvider,
                bedrockRegion);
    }

    public FetchConfig getFetchConfig() {
        return new FetchConfig(
                maxFileSizeChars,
                (long) maxTotalContextChars,
                maxFileSizeBytes,
                contextMode.name());
    }

    public JiraConfig getJiraConfig() {
        return new JiraConfig(jiraSecretArn, stateMachineArn);
    }

    public BitbucketConfig getBitbucketConfig() {
        return new BitbucketConfig(bitbucketSecretArn);
    }

    public AgentConfig getAgentConfig() {
        return new AgentConfig(
                ConfigLoader.getBooleanEnv("AGENT_ENABLED", false),
                ConfigLoader.getRequiredEnv("AGENT_QUEUE_URL"),
                ConfigLoader.getIntEnv("AGENT_MAX_TURNS", 10),
                ConfigLoader.getIntEnv("AGENT_MAX_WALL_CLOCK_SECONDS", 600),
                ConfigLoader.getEnv("AGENT_TRIGGER_PREFIX", "@ai"),
                ConfigLoader.getIntEnv("AGENT_TOKEN_BUDGET", 50000),
                ConfigLoader.getIntEnv("AGENT_RECENT_MESSAGES_TO_KEEP", 2),
                ConfigLoader.getBooleanEnv("AGENT_GUARDRAILS_ENABLED", true),
                ConfigLoader.getIntEnv("AGENT_COST_BUDGET_PER_TICKET", 200000),
                ConfigLoader.getBooleanEnv("AGENT_CLASSIFIER_USE_LLM", false),
                ConfigLoader.getEnv("AGENT_MENTION_KEYWORD", "ai"),
                System.getenv("AGENT_BOT_ACCOUNT_ID"));
    }

    /**
     * MCP server configurations as JSON string from environment.
     * Format: JSON array of McpServerConfig objects.
     * 
     * @deprecated Use MCP Gateway instead via {@link #getMcpGatewayUrl()}
     */
    @Deprecated
    public String getMcpServersConfig() {
        return ConfigLoader.getEnv("MCP_SERVERS_CONFIG", "[]");
    }

    /**
     * URL of the MCP Gateway Lambda Function URL.
     * When set, all MCP tool calls are routed through the unified gateway.
     */
    public Optional<String> getMcpGatewayUrl() {
        String url = ConfigLoader.getEnv("MCP_GATEWAY_URL", null);
        return Optional.ofNullable(url).filter(s -> !s.isBlank());
    }

    /**
     * Whether the MCP Gateway is enabled.
     */
    public boolean isMcpGatewayEnabled() {
        return ConfigLoader.getBooleanEnv("MCP_GATEWAY_ENABLED", false);
    }

    public Optional<String> getStateMachineArn() {
        return Optional.ofNullable(stateMachineArn);
    }

    public Optional<String> getJiraWebhookSecret() {
        return Optional.ofNullable(jiraWebhookSecret);
    }

    /**
     * ARN of the Secrets Manager secret holding the Jira webhook pre-shared token.
     * Present when deployed via CDK; absent in local test runs (uses raw env var
     * instead).
     */
    public Optional<String> getJiraWebhookSecretArn() {
        return Optional.ofNullable(jiraWebhookSecretArn);
    }

    /**
     * ARN of the Secrets Manager secret holding the GitHub agent webhook HMAC
     * secret.
     * Used by {@code AgentWebhookHandler} to verify {@code X-Hub-Signature-256} on
     * GitHub events.
     */
    public String getGitHubAgentWebhookSecretArn() {
        return gitHubAgentWebhookSecretArn;
    }

    public ContextMode getContextMode() {
        return contextMode;
    }

    public enum ContextMode {
        FULL_REPO,
        INCREMENTAL
    }

    public record SlackConfig(
            Optional<String> webhookUrl,
            Optional<String> channel,
            boolean fallbackToJira) {
    }
}
